@startuml

title __STUDENTSYSTEMLEARN's Class Diagram__\n

  namespace com.example.studentsystemlearn {
    class com.example.studentsystemlearn.StudentSystemLearnApplication {
    }
  }
  

  namespace com.example.studentsystemlearn {
    namespace controller {
      class com.example.studentsystemlearn.controller.StudentController {
      }
    }
  }
  

  namespace com.example.studentsystemlearn {
    namespace entity {
      class com.example.studentsystemlearn.entity.Student {
      }
    }
  }
  

  namespace com.example.studentsystemlearn {
    namespace repository {
      interface com.example.studentsystemlearn.repository.StudentRepository {
      }
    }
  }
  

  namespace com.example.studentsystemlearn {
    namespace service {
      class com.example.studentsystemlearn.service.StudentService {
      }
    }
  }
  

  namespace com.example.studentsystemlearn {
    namespace service {
      interface com.example.studentsystemlearn.service.StudentServiceInterface {
      }
    }
  }
  

  com.example.studentsystemlearn.StudentSystemLearnApplication .up.|> org.springframework.boot.CommandLineRunner
  com.example.studentsystemlearn.StudentSystemLearnApplication o-- com.example.studentsystemlearn.repository.StudentRepository : studentRepository
  com.example.studentsystemlearn.controller.StudentController o-- com.example.studentsystemlearn.service.StudentServiceInterface : studentService
  com.example.studentsystemlearn.service.StudentService .up.|> com.example.studentsystemlearn.service.StudentServiceInterface
  com.example.studentsystemlearn.service.StudentService o-- com.example.studentsystemlearn.repository.StudentRepository : studentRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
