# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine



# Expose port 8080 for the application
EXPOSE 8080

# Set the entry point to run the application
ENTRYPOINT ["java", "-jar", "target/P2010-0.0.1-SNAPSHOT.jar"]